[project]
name = "pt-asset-tool"
version = "0.1.0"
description = ""
authors = [{ name = "Landon Manning", email = "lmanning17@gmail.com" }]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pillow (>=11.2.1,<12.0.0)",
    "pygltflib (>=1.16.4,<2.0.0)",
    "numpy (>=2.3.0,<3.0.0)",
]

[dependency-groups]
dev = ["pytest"]

[tool.uv]
default-groups = "all"

[tool.hatch.build.targets.sdist]
include = [
    "src/pt",
    "src/app",
]

[tool.hatch.build.targets.wheel]
include = [
    "src/pt",
    "src/app",
]

[tool.hatch.build.targets.wheel.sources]
"src/pt" = "pt"
"src/app" = "app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
